<ThemedBoxLayout>:
    padding: dp(5)
    spacing: dp(3)

<AppMenu>:
    size_hint: (None, None)
    padding: [self.padding[0], 0, self.padding[2], 0] if self.orientation == "horizontal" else [0, self.padding[1], 0, self.padding[3]]

<MenuLayout@RelativeLayout>:
    padding: dp(5)
    spacing: dp(3)

<PuzzleLayout>:
    padding: dp(50)  # FIXME: this is not actually applied

<SelectableRecycleBoxLayout>:
    padding: dp(0)
