FROM ghcr.io/kivy/buildozer:latest
# See https://github.com/kivy/buildozer/blob/master/Dockerfile

# By default Python buffers output and you see prints after execution
# Set env variable to disable this behavior
ENV PYTHONUNBUFFERED=1

# Set venv vars
ENV VIRTUAL_ENV=$HOME_DIR/.venv
