name: Build EXE file w/ PyInstaller GH Action
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  # push:
  #   branches:
  #     - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install build prereqs
        shell: powershell
        run: |
          # Install OpenGL support
          $version = "26.1.1"
          $url = "https://github.com/pal1000/mesa-dist-win/releases/download/$version/mesa3d-$version-release-mingw.7z"
          Invoke-WebRequest -Uri "$url" -OutFile "mesa.7z"
          & "${env:ProgramFiles}/7-Zip/7z.exe" x "mesa.7z" -o"mesa" -y
          dir ./mesa/x64
          # Copy DLLs to current directory.
          #Copy-Item "mesa/x64/*" -Destination "."
          # Add DLLs folder to $PATH
          $env:Path += ";${{ env.GITHUB_WORKSPACE }}/mesa/x64/"

      - name: Build EXE with PyInstaller Action
        uses: n8marti/pyinstaller@main
        id: pyinstaller
        with:
          spec: ./pyinstaller.spec
          pyproject: ./pyproject.toml
          python_ver: "3.12"
          upload_exe_with_name: "NetworkPuzzles"
          clean_checkout: false # don't remove existing files from workdir

      - name: Check sys info
        if: always()
        shell: bash
        run: |
          env | sort
          ls -l ${RUNNER_TOOL_CACHE}/Python/*/x64/Scripts/

      - name: Upload kivy logs
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: kivy-logs
          path: ${HOME}/.kivy/logs/*.txt

      - name: Upload pyinstaller logs
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: pyinstaller-logs
          path: ${{ github.workspace }}/build/pyinstaller/*.txt
