name: Build EXE file w/ PyInstaller GH Action
on:
  workflow_call:
    outputs:
      filename:
        value: ${{ jobs.build.outputs.binary }}
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/*exe*"
      - "src/network_puzzles/**"
  # push:
  #   branches:
  #     - main

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 60
    outputs:
      binary: ${{ steps.pyinstaller.outputs.binary }}
    steps:
      - uses: actions/checkout@v7

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.12

      - name: Install Python dev tools
        shell: bash
        run: |
          python -m pip install -U pip
          python -m pip install wheel setuptools

      - name: Install project
        shell: bash
        run: python -m pip install .

      # - name: Run tests
      #   shell: bash
      #   run: |
      #     ./scripts/test-puzzles.sh 2>/dev/null  # CLI tests
      #     # ./scripts/run-tests.sh  # GUI tests; DISPLAY needed

      # - name: Ensure localization binaries  # needs gettext binaries
      #   shell: bash
      #   run: ./scripts/update-locales.sh mo

      - name: Install PyInstaller
        shell: bash
        run: |
          python -m pip install pyinstaller
          # Install Kivy window/audio dependencies explicitly for Windows
          # python -m pip install kivy.deps.sdl2 kivy.deps.glew pypiwin32

      - name: Run EXE PyInstaller
        id: pyinstaller
        shell: bash
        env:
          KIVY_NO_CONSOLELOG: 1 # avoid duplicate console logging
          KIVY_GL_BACKEND: dummy # prevents openGL error in spite of ValueError
          PYI_LOG_LEVEL: DEBUG
        run: |
          pyinstaller \
            --clean \
            --noconfirm \
            pyinstaller.spec 2>&1 | tee pyinstaller.log
          echo "binary=./dist/NetworkPuzzles.exe" >> $GITHUB_OUTPUT

      - name: Log EXE build/dist files
        if: always()
        shell: bash
        run: |
          echo "build:" | tee -a pyinstaller-files.txt
          ls -l build/ | tee -a pyinstaller-files.txt
          echo "build/pyinstaller:" | tee -a pyinstaller-files.txt
          ls -l build/pyinstaller/ | tee -a pyinstaller-files.txt
          echo "dist:" | tee -a pyinstaller-files.txt
          ls -l dist/ | tee -a pyinstaller-files.txt

      - name: Upload EXE package
        if: ${{ steps.pyinstaller.conclusion == 'success' }}
        id: exe_upload
        uses: actions/upload-artifact@v7
        with:
          path: ./dist/NetworkPuzzles.exe
          archive: false

      # - name: Upload EXE to draft release
      #   shell: bash
      #   if: ${{ github.event_name == 'push' }}
      #   env:
      #     GITHUB_TOKEN: ${{ github.TOKEN }}
      #   run: gh release upload ${{ inputs.tag_name }} ./dist/NetworkPuzzles.exe --clobber

      - name: Upload EXE build files
        if: ${{ steps.pyinstaller.conclusion == 'success' }}
        uses: actions/upload-artifact@v7
        with:
          name: pyinstaller-build-files
          path: ./build/pyinstaller

      # - name: Run DIR PyInstaller
      #   id: pyinstaller-dir
      #   shell: bash
      #   env:
      #     KIVY_NO_CONSOLELOG: 1 # avoid duplicate console logging
      #     KIVY_GL_BACKEND: dummy # prevents openGL error in spite of ValueError
      #     PYI_LOG_LEVEL: DEBUG
      #   run: |
      #     pyinstaller \
      #       --clean \
      #       --noconfirm \
      #       pyinstaller-dir.spec 2>&1 | tee pyinstaller-dir.log

      # - name: Log DIR build/dist files
      #   if: always()
      #   shell: bash
      #   run: |
      #     echo "build:" | tee -a pyinstaller-dir-files.txt
      #     ls -l build/ | tee -a pyinstaller-dir-files.txt
      #     echo "build/pyinstaller-dir:" | tee -a pyinstaller-dir-files.txt
      #     ls -l build/pyinstaller-dir/ | tee -a pyinstaller-dir-files.txt
      #     echo "dist:" | tee -a pyinstaller-dir-files.txt
      #     ls -l dist/ | tee -a pyinstaller-dir-files.txt

      # - name: Upload DIR package
      #   if: ${{ steps.pyinstaller-dir.conclusion == 'success' }}
      #   id: dir_upload
      #   uses: actions/upload-artifact@v7
      #   with:
      #     name: pyinstaller-dir
      #     path: ./dist
      #     compression-level: 0

      # - name: Upload DIR build files
      #   if: ${{ steps.pyinstaller-dir.conclusion == 'success' }}
      #   uses: actions/upload-artifact@v7
      #   with:
      #     name: pyinstaller-dir-build-files
      #     path: ./build/pyinstaller-dir

      - name: Upload kivy & pyinstaller logs
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: pyinstaller-logs
          # include-hidden-files: true  # needed for .kivy dir
          path: |
            # ~\\.kivy\\logs\\*.txt  # different root; requires separate step
            *.log
            pyinstaller*.txt
            build/pyinstaller/*.txt
