name: Build APK file on system
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - fix-buildozer-action
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest # apt deps below are for 26.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install dependencies
      # ref: https://buildozer.readthedocs.io/en/latest/installation/#install-on-ubuntu-26-04
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            autoconf \
            automake \
            autopoint \
            cmake \
            gettext \
            git \
            libffi-dev \
            libncurses5-dev \
            libncursesw5-dev \
            libssl-dev \
            libtinfo6 \
            libtool \
            pkg-config \
            unzip \
            zip \
            zlib1g-dev
            # openjdk-17-jdk \
            # python3-pip \
            # python3-virtualenv \

      # Set up Java 17 required by Gradle
      - name: Setup Java 17 required by Gradle
        uses: actions/setup-java@v5
        with:
          distribution: "temurin" # or 'zulu', 'liberica', etc.
          java-version: "17"

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      # # Install pip dependencies
      # - name: Install pip dependencies
      #   run: |
      #     pip install --upgrade pip
      #     pip install cython==0.29.33 setuptools

      - name: Install app python package
        run: python3 -m pip install .[build]

      # # Cache Buildozer files.  # doesn't seem to speed anything up
      # - name: Cache Buildozer global directory
      #   uses: actions/cache@v4
      #   with:
      #     path: .buildozer_global
      #     key: buildozer-global-${{ hashFiles('buildozer.spec') }} # Replace with your path

      # Build with Buildozer
      - name: Build with Buildozer
        id: buildozer
        run: |
          yes | buildozer -v android debug
          ls -l
      # - name: Build with Buildozer Action
      #   #uses: ArtemSBulgakov/buildozer-action@v1
      #   uses: n8marti/buildozer-action@fix-user-doesnt-exist
      # id: buildozer

      # Upload artifacts
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
