name: Create draft release
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: read

jobs:
  run-tests:
    uses: ./.github/workflows/run-tests.yml

  build-exe:
    needs: run-tests
    uses: ./.github/workflows/build-exe-pyinstaller.yml

  build-apk:
    needs: run-tests
    uses: ./.github/workflows/build-apk-docker-image.yml

  update-release-draft:
    needs: [build-apk, build-exe]
    runs-on: ubuntu-latest
    steps:
      - name: prepare release draft
        id: release
        uses: release-drafter/release-drafter@v7

      - name: upload EXE
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        run: gh release upload ${{ steps.release.outputs.tag_name }} ${{ needs.build-exe.outputs.filename }} --clobber

      - name: upload APK
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        run: gh release upload ${{ steps.release.outputs.tag_name }} ${{ needs.build-apk.outputs.filename }} --clobber

  update-prerelease-draft:
    needs: [build-apk, build-exe]
    runs-on: ubuntu-latest
    steps:
      - name: prepare prerelease draft
        id: prerelease
        uses: release-drafter/release-drafter@v7
        with:
          prerelease: true
          prerelease-identifier: "rc"

      - name: upload EXE
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        run: gh release upload ${{ steps.prerelease.outputs.tag_name }} ${{ needs.build-exe.outputs.filename }} --clobber

      - name: upload APK
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        run: gh release upload ${{ steps.prerelease.outputs.tag_name }} ${{ needs.build-apk.outputs.filename }} --clobber
