name: Create draft release
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: read

jobs:
  update-release-draft:
    outputs:
      tag_name: steps.release.tag_name
    runs-on: ubuntu-latest
    steps:
      - name: prepare release draft
        id: release
        uses: release-drafter/release-drafter@v7

  update-prerelease-draft:
    outputs:
      tag_name: steps.prerelease.tag_name
    runs-on: ubuntu-latest
    steps:
      - name: prepare prerelease draft
        id: prerelease
        uses: release-drafter/release-drafter@v7
        with:
          prerelease: true
          prerelease-identifier: "rc"

  run-tests:
    uses: ./.github/workflows/run-tests.yml

  build-exe:
    needs: run-tests
    uses: ./.github/workflows/build-exe-pyinstaller.yml

  build-apk:
    needs: run-tests
    uses: ./.github/workflows/build-apk-docker-image.yml

  upload-exes:
    needs: [build-exe, update-prerelease-draft, update-release-draft]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: NetworkPuzzles.exe
          
      - name: upload prerelease EXE
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        run: gh release upload ${{ needs.update-prerelease-draft.outputs.tag_name }} NetworkPuzzles.exe --clobber

      - name: upload release EXE
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        run: gh release upload ${{ needs.update-release-draft.outputs.tag_name }} NetworkPuzzles.exe --clobber

  upload-apks:
    needs: [build-apk, update-prerelease-draft, update-release-draft]
    runs-on: ubuntu-latest
    steps:
      - name: upload prerelease APK
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        run: gh release upload ${{ needs.update-prerelease-draft.outputs.tag_name }} ${{ needs.build-apk.outputs.filename }} --clobber

      - name: upload release APK
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        run: gh release upload ${{ needs.update-release-draft.outputs.tag_name }} ${{ needs.build-apk.outputs.filename }} --clobber
