name: Run pre-build tests
on:
  workflow_call:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12" #set your python version

      - name: Install app python package
        run: pip install .

      - run: |
          ./scripts/test-puzzles.sh 2>/dev/null  # CLI tests
          # ./scripts/run-tests.sh  # GUI tests; DISPLAY needed
