name: Run pre-build tests
on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "src/network_puzzles/**"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12" #set your python version

      - name: Install app python package
        run: pip install .

      - run: |
          echo "CLI tests"
          ./scripts/test-puzzles.sh 2>/dev/null  # CLI tests
          echo -e "\n\nGUI tests"
          ./scripts/run-tests.sh  # GUI tests
